import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "./components/Navigation";
import Footer from "./components/Footer";

// Import fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Crypto Dashboard",
  description: "Generated by PAGE Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/img/favicon/favicon-16x16.png" />
        <title>Crypto Dashboard</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-indigo-50`} // Apply global background color
      >
        <Navigation /> {/* Render the Navigation component */}
        <main>{children}</main> {/* Main content */}
        <Footer /> {/* Render the Footer component */}
      </body>
    </html>
  );
}
